#!/usr/bin/env python3
"""Build from any cwd using system tools or the project's private Dart Sass."""
import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import json
import hashlib
from factory import validate

ROOT = Path(__file__).resolve().parents[1]

def environment():
    env = os.environ.copy()
    local = ROOT / '.tools/dart-sass'
    if local.is_dir():
        env['PATH'] = str(local) + os.pathsep + env.get('PATH', '')
    env.setdefault('HUGO_CACHEDIR', str(Path(tempfile.gettempdir()) / 'website-starter-hugo-cache'))
    return env


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def publish_output(source, destination):
    """Reconcile owned output. Refuse every target the manifest does not own, before writing anything."""
    manifest = destination / '.factory-build.json'
    if destination.is_symlink() or manifest.is_symlink():
        raise ValueError('Destination or output manifest is a symlink; refusing to write through it.')
    previous = json.loads(manifest.read_text()) if manifest.is_file() else {}
    if not isinstance(previous, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in previous.items()):
        raise ValueError('Output manifest is malformed. Choose an empty destination.')
    current = {p.relative_to(source).as_posix(): digest(p) for p in source.rglob('*') if p.is_file()}
    stale = set(previous) - set(current)
    conflicts = []
    for name in sorted(set(current) | stale):
        parts = Path(name).parts
        if Path(name).is_absolute() or '..' in parts:
            raise ValueError(f'Invalid output manifest path: {name}')
        path = destination / name
        if any(destination.joinpath(*parts[:i+1]).is_symlink() for i in range(len(parts))):
            conflicts.append(f'{name}: symlink in generated output')
        elif path.is_dir():
            conflicts.append(f'{name}: destination is a directory, not a file')
        elif path.exists() and name not in previous:
            conflicts.append(f'{name}: exists but was not generated by this factory')
        elif path.exists() and digest(path) != previous[name]:
            conflicts.append(f'{name}: edited since the last build')
    if destination.is_dir():
        for path in destination.rglob('*.html'):
            name = path.relative_to(destination).as_posix()
            if name not in current and name not in previous:
                conflicts.append(f'{name}: untracked HTML would remain')
    if conflicts:
        raise ValueError('Refusing to write generated output; nothing was changed:\n  ' + '\n  '.join(conflicts)
                         + '\nChoose an empty destination or restore these files.')
    # ponytail: preflight only, no rollback journal. A copy failing mid-loop still leaves a mixed tree;
    # add staged directory swap if that ever bites. Same for concurrent builds — no destination lock.
    destination.mkdir(parents=True, exist_ok=True)
    for name in current:
        path = destination / name
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source / name, path)
    for name in stale:
        (destination / name).unlink(missing_ok=True)
    pending = manifest.with_suffix('.json.tmp')
    pending.write_text(json.dumps(current, indent=2)+'\n')
    os.replace(pending, manifest)

def content_selection(destination):
    config = json.loads((ROOT/'data/factory.json').read_text())
    profile = json.loads((ROOT/'data/presets'/f"{config['preset']}.json").read_text())
    shutil.copytree(ROOT/'content', destination)
    for path in destination.iterdir():
        if path.is_dir() and path.name not in profile['pages']:
            if path.name != 'site-kit' or not config['workshop']:
                shutil.rmtree(path)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--destination', default='public')
    parser.add_argument('--base-url')
    parser.add_argument('--serve', action='store_true')
    parser.add_argument('--port', type=int, default=1313)
    args = parser.parse_args()
    errors = validate(ROOT)
    if errors:
        parser.error("Invalid factory configuration:\n" + "\n".join(errors))
    env = environment()
    for binary, pin in [('hugo', '.hugo-version'), ('sass', '.sass-version')]:
        exe = shutil.which(binary, path=env['PATH'])
        if not exe:
            parser.error(f'{binary} is missing. See README.md; run scripts/setup.py for Dart Sass.')
        command = [exe, 'version' if binary == 'hugo' else '--version']
        result = subprocess.run(command, env=env, cwd=ROOT, capture_output=True, text=True)
        version = (ROOT / pin).read_text().strip()
        if result.returncode or not re.search(r'(?<![\d.])' + re.escape(version) + r'(?![\d.])', result.stdout):
            parser.error(f'{binary}: expected {version}; found {result.stdout.strip() or result.stderr.strip()}')
        if binary == 'hugo' and '+extended' not in result.stdout:
            parser.error('Hugo Extended is required.')
    cmd = ['hugo', '--minify', '--gc']
    if args.base_url:
        cmd += ['--baseURL', args.base_url]
    destination = (ROOT/args.destination).absolute()
    resolved = destination.resolve()
    if resolved == ROOT or resolved in ROOT.parents or any(resolved == ROOT/x or ROOT/x in resolved.parents for x in ('assets','content','data','layouts','static','scripts','docs','node_modules','.tools')):
        parser.error('Destination must be a build directory, never a source or parent directory.')
    try:
        with tempfile.TemporaryDirectory(prefix='factory-build-') as temporary:
            temporary = Path(temporary)
            content_selection(temporary/'content')
            output = temporary/'output'
            result = subprocess.run(cmd + ['--contentDir',str(temporary/'content'),'--destination',str(output)], cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            if result.returncode or re.search(r'(?m)^WARN\b', result.stdout):
                print(result.stdout, file=sys.stderr)
                return result.returncode or 1
            from check_site import check
            errors = check(output.resolve())
            if errors:
                print('\n'.join(errors),file=sys.stderr)
                return 1
            publish_output(output, destination)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(f'Build and generated-output checks passed: {args.destination}')
    if args.serve:
        from functools import partial
        from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
        handler = partial(SimpleHTTPRequestHandler, directory=str(destination))
        with ThreadingHTTPServer(('127.0.0.1', args.port), handler) as server:
            print(f'Preview: http://127.0.0.1:{args.port}/ — serving verified output; rebuild after edits.', flush=True)
            try:
                server.serve_forever()
            except KeyboardInterrupt:
                pass
    return 0

if __name__ == '__main__':
    sys.exit(main())
