#!/usr/bin/env python3
"""Generate JSON Schemas from data/modules.json and data/tones.json.

  python3 scripts/schemas.py          # write schemas/*.schema.json
  python3 scripts/schemas.py --check  # fail if the committed files are out of date

schemas/preset.schema.json  - data/presets/<slug>.json (editors, agents, and LLM output)
schemas/plan.schema.json    - an AI-drafted page plan (scripts/draft_plan.py structured output)

The schemas describe shape. Cross-references (a section's content key, links to omitted
pages, image files) stay with scripts/factory.py, which remains the authority.
Also provides validate(instance, schema): a small checker for the keywords used here, so
tests and the MCP server need no third-party package.
"""
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'schemas'
# Classifying scope as included/excluded or fit/not-fit is a business decision, so an AI
# draft may not choose these modules; a person adds them in the planner.
HUMAN_ONLY = {'fit', 'inclusions'}

def load():
    return json.loads((ROOT/'data/modules.json').read_text()), json.loads((ROOT/'data/tones.json').read_text())

def preset_schema(registry, tones):
    text = {'$ref': '#/$defs/text'}
    action = {'$ref': '#/$defs/action'}
    shared = {'text': {'type': 'string', 'minLength': 1},
              'action': {'type': 'object', 'required': ['label', 'url'],
                         'properties': {'label': text, 'url': {'type': 'string', 'pattern': '^/'}}}}
    item = {'type': 'object', 'required': ['title', 'text'],
            'properties': {'title': text, 'text': text, 'url': {'type': 'string', 'pattern': '^/'},
                           'image': {'type': 'string'}}}
    content = {}
    for key, module in registry.items():
        props = {f: text for f in ('title', 'intro', 'body', 'notice', 'label', 'aside', 'note')}
        props.update(action=action, secondary=action)
        if 'items' in module['required']:
            entry = json.loads(json.dumps(item))
            entry['required'] = ['title', 'text', *module.get('item_required', [])]
            for field in module.get('item_required', []):
                entry['properties'].setdefault(field, text)
            for field, choices in module.get('item_choices', {}).items():
                entry['properties'][field] = {'enum': choices}
            props['items'] = {'type': 'array', 'minItems': 1, 'items': entry}
        content[f'content-{key}'] = {'type': 'object', 'description': f"{module['name']}: {module['purpose']}",
                                     'required': module['required'], 'properties': props}
    section = {
        'type': 'object', 'required': ['module', 'variant', 'content'], 'additionalProperties': False,
        'properties': {'module': {'enum': list(registry)}, 'variant': {'type': 'string'},
                       'content': {'type': 'string', 'description': 'Key in this preset\'s "sections" object'}},
        'allOf': [{'if': {'properties': {'module': {'const': key}}},
                   'then': {'properties': {'variant': {'enum': module['variants']}}}} for key, module in registry.items()],
    }
    page = {'type': 'object', 'required': ['title', 'description', 'sections'],
            'properties': {'title': text, 'description': text,
                           'sections': {'type': 'array', 'minItems': 1, 'items': section}}}
    return {
        '$schema': 'https://json-schema.org/draft/2020-12/schema',
        '$id': 'https://258webco.com/schemas/preset.schema.json',
        'title': 'Website factory preset',
        'description': 'Generated by scripts/schemas.py from data/modules.json. Run scripts/factory.py for full validation.',
        'type': 'object',
        'required': ['name', 'label', 'tone', 'pages', 'sections'],
        'properties': {
            'name': text, 'label': text, 'description': {'type': 'string'},
            'tone': {'enum': list(tones)},
            'pages': {'type': 'object', 'required': ['home', 'contact'],
                      'patternProperties': {'^[a-z][a-z0-9-]*$': page}, 'additionalProperties': False},
            'sections': {'type': 'object', 'additionalProperties': {'type': 'object'}},
            'approved_claims': {'type': 'array', 'items': text,
                                'description': 'Claims the business has confirmed; see scripts/claims.py'},
        },
        '$defs': {**shared, **content},
    }

def plan_schema(registry):
    """Structured-output schema for an AI draft. Every object is closed and every field
    required (empty strings allowed), as structured outputs expect."""
    s = {'type': 'string'}
    strings = {'type': 'array', 'items': s}
    def closed(props):
        return {'type': 'object', 'properties': props, 'required': list(props), 'additionalProperties': False}
    section = closed({'kind': {'enum': [k for k in registry if k not in HUMAN_ONLY]},
                      'variant': s, 'title': s, 'body': s, 'cta': s})
    page = closed({'name': s, 'purpose': s, 'action': s, 'sections': {'type': 'array', 'items': section}})
    return {
        '$schema': 'https://json-schema.org/draft/2020-12/schema',
        '$id': 'https://258webco.com/schemas/plan.schema.json',
        'title': 'AI-drafted website plan',
        'description': 'Generated by scripts/schemas.py. Output shape for scripts/draft_plan.py.',
        **closed({'name': s, 'business': s, 'audience': s, 'goal': s, 'facts': strings,
                  'unknowns': strings, 'pages': {'type': 'array', 'items': page}}),
    }

def generated():
    registry, tones = load()
    return {'preset.schema.json': preset_schema(registry, tones), 'plan.schema.json': plan_schema(registry)}

def validate(instance, schema, root=None, path='$'):
    """Return a list of 'path: problem' strings for the JSON Schema keywords these files use."""
    root = root or schema
    if '$ref' in schema:
        target = root
        for part in schema['$ref'].lstrip('#/').split('/'):
            target = target[part]
        return validate(instance, target, root, path)
    errors = []
    kind = schema.get('type')
    types = {'object': dict, 'array': list, 'string': str, 'boolean': bool}
    if kind in types and not isinstance(instance, types[kind]):
        return [f'{path}: expected {kind}']
    if 'const' in schema and instance != schema['const']:
        errors.append(f'{path}: must be {schema["const"]!r}')
    if 'enum' in schema and instance not in schema['enum']:
        errors.append(f'{path}: {instance!r} is not one of {schema["enum"]}')
    if isinstance(instance, str):
        if len(instance) < schema.get('minLength', 0):
            errors.append(f'{path}: must not be empty')
        if 'pattern' in schema and not re.search(schema['pattern'], instance):
            errors.append(f'{path}: does not match {schema["pattern"]}')
    if isinstance(instance, list):
        if len(instance) < schema.get('minItems', 0):
            errors.append(f'{path}: needs at least {schema["minItems"]} item(s)')
        if 'items' in schema:
            for i, value in enumerate(instance):
                errors += validate(value, schema['items'], root, f'{path}[{i}]')
    if isinstance(instance, dict):
        for field in schema.get('required', []):
            if field not in instance:
                errors.append(f'{path}: missing {field}')
        props, patterns = schema.get('properties', {}), schema.get('patternProperties', {})
        for key, value in instance.items():
            matched = False
            if key in props:
                matched = True
                errors += validate(value, props[key], root, f'{path}.{key}')
            for pattern, sub in patterns.items():
                if re.search(pattern, key):
                    matched = True
                    errors += validate(value, sub, root, f'{path}.{key}')
            extra = schema.get('additionalProperties', True)
            if not matched and extra is False:
                errors.append(f'{path}: unexpected field {key}')
            elif not matched and isinstance(extra, dict):
                errors += validate(value, extra, root, f'{path}.{key}')
    for sub in schema.get('allOf', []):
        if 'if' in sub:
            if not validate(instance, sub['if'], root, path):
                errors += validate(instance, sub.get('then', {}), root, path)
        else:
            errors += validate(instance, sub, root, path)
    return errors

def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    stale = []
    for name, schema in generated().items():
        text = json.dumps(schema, indent=2) + '\n'
        target = OUT / name
        if '--check' in argv:
            if not target.is_file() or target.read_text() != text:
                stale.append(name)
        else:
            OUT.mkdir(exist_ok=True)
            target.write_text(text)
    if stale:
        print('Out of date: ' + ', '.join(f'schemas/{n}' for n in stale) + '. Run python3 scripts/schemas.py.', file=sys.stderr)
        return 1
    print('Schemas are up to date.' if '--check' in argv else f'Wrote {len(generated())} schemas to schemas/.')
    return 0

if __name__ == '__main__':
    sys.exit(main())
